import 'package:flutter/material.dart';

const kStyle = TextStyle(fontSize: 20.0, fontWeight: FontWeight.bold);
List<String> symptoms = [
  ' abdominal_pain',
  ' abnormal_menstruation',
  ' acidity',
  ' acute_liver_failure',
  ' altered_sensorium',
  ' anxiety',
  ' back_pain',
  ' belly_pain',
  ' blackheads',
  ' bladder_discomfort',
  ' blister',
  ' blood_in_sputum',
  ' bloody_stool',
  ' blurred_and_distorted_vision',
  ' breathlessness',
  ' brittle_nails',
  ' bruising',
  ' burning_micturition',
  ' chest_pain',
  ' chills',
  ' cold_hands_and_feets',
  ' coma',
  ' congestion',
  ' constipation',
  ' continuous_feel_of_urine',
  ' continuous_sneezing',
  ' cough',
  ' cramps',
  ' dark_urine',
  ' dehydration',
  ' depression',
  ' diarrhoea',
  ' dischromic _patches',
  ' distention_of_abdomen',
  ' dizziness',
  ' drying_and_tingling_lips',
  ' enlarged_thyroid',
  ' excessive_hunger',
  ' extra_marital_contacts',
  ' family_history',
  ' fast_heart_rate',
  ' fatigue',
  ' fluid_overload',
  ' foul_smell_of urine',
  ' headache',
  ' high_fever',
  ' hip_joint_pain',
  ' history_of_alcohol_consumption',
  ' increased_appetite',
  ' indigestion',
  ' inflammatory_nails',
  ' internal_itching',
  ' irregular_sugar_level',
  ' irritability',
  ' irritation_in_anus',
  ' joint_pain',
  ' knee_pain',
  ' lack_of_concentration',
  ' lethargy',
  ' loss_of_appetite',
  ' loss_of_balance',
  ' loss_of_smell',
  ' malaise',
  ' mild_fever',
  ' mood_swings',
  ' movement_stiffness',
  ' mucoid_sputum',
  ' muscle_pain',
  ' muscle_wasting',
  ' muscle_weakness',
  ' nausea',
  ' neck_pain',
  ' nodal_skin_eruptions',
  ' obesity',
  ' pain_behind_the_eyes',
  ' pain_during_bowel_movements',
  ' pain_in_anal_region',
  ' painful_walking',
  ' palpitations',
  ' passage_of_gases',
  ' patches_in_throat',
  ' phlegm',
  ' polyuria',
  ' prominent_veins_on_calf',
  ' puffy_face_and_eyes',
  ' pus_filled_pimples',
  ' receiving_blood_transfusion',
  ' receiving_unsterile_injections',
  ' red_sore_around_nose',
  ' red_spots_over_body',
  ' redness_of_eyes',
  ' restlessness',
  ' runny_nose',
  ' rusty_sputum',
  ' scurring',
  ' shivering',
  ' silver_like_dusting',
  ' sinus_pressure',
  ' skin_peeling',
  ' skin_rash',
  ' slurred_speech',
  ' small_dents_in_nails',
  ' spinning_movements',
  ' spotting_ urination',
  ' stiff_neck',
  ' stomach_bleeding',
  ' stomach_pain',
  ' sunken_eyes',
  ' sweating',
  ' swelled_lymph_nodes',
  ' swelling_joints',
  ' swelling_of_stomach',
  ' swollen_blood_vessels',
  ' swollen_extremeties',
  ' swollen_legs',
  ' throat_irritation',
  ' toxic_look_(typhos)',
  ' ulcers_on_tongue',
  ' unsteadiness',
  ' visual_disturbances',
  ' vomiting',
  ' watering_from_eyes',
  ' weakness_in_limbs',
  ' weakness_of_one_body_side',
  ' weight_gain',
  ' weight_loss',
  ' yellow_crust_ooze',
  ' yellow_urine',
  ' yellowing_of_eyes',
  ' yellowish_skin',
  'itching'
];

List<dynamic> doctors = [
  {
    "name": "Aditi Musunur",
    "phone": 913852485394,
    "lat": 37.397496627282315,
    "long": -122.0798959343522,
    "opening": "1:00 pm",
    "closing": "10:00pm",
    "diseases": [
      'Fungal infection',
      'Allergy',
      'GERD',
      'Chronic cholestasis',
    ]
  },
  {
    "name": "Advitiya Sujeet",
    "phone": 913858157499,
    "lat": 37.39558735491914,
    "long": -122.10289856005706,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": [
      'Drug Reaction',
      'Peptic ulcer diseae',
      'AIDS',
      'Diabetes ',
    ]
  },
  {
    "name": "Alagesan Poduri",
    "phone": 913852455308,
    "lat": 37.37812889540654,
    "long": -122.0970620729379,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": ['Urinary tract infection', 'Psoriasis', 'Impetigo']
  },
  {
    "name": "Amrish Ilyas",
    "phone": 913859727320,
    "lat": 37.35506951561769,
    "long": -122.08652999669111,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": [
      'Osteoarthristis',
      'Arthritis',
      '(vertigo) Paroymsal  Positional Vertigo',
      'Acne',
    ]
  },
  {
    "name": "Aditi Musunur",
    "phone": 913859415623,
    "lat": 37.3997999445519,
    "long": -122.0557269667435,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": [
      'Hypothyroidism',
      'Hyperthyroidism',
      'Hypoglycemia',
    ]
  },
  {
    "name": "Avantas Ghosal",
    "phone": 913859003021,
    "lat": 37.37400469541573,
    "long": -122.08028389604502,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": [
      'Dimorphic hemmorhoids(piles)',
      'Heart attack',
      'Varicose veins',
    ]
  },
  {
    "name": "Avidosa Vaisakhi",
    "phone": 913857924730,
    "lat": 37.39186389008355,
    "long": -122.05697562416562,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": [
      'Alcoholic hepatitis',
      'Tuberculosis',
      'Common Cold',
      'Pneumonia',
    ]
  },
  {
    "name": "Asvathama Ponnada",
    "phone": 913859431392,
    "lat": 37.39550135268882,
    "long": -122.08153255346711,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": [
      'Cervical spondylosis',
      'Paralysis (brain hemorrhage)',
      'Jaundice',
    ]
  },
  {
    "name": "Aprativirya Seshan",
    "phone": 913858056851,
    "lat": 37.37036618986452,
    "long": -122.0881920597184,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": [
      'Alcoholic hepatitis',
      'Tuberculosis',
      'Common Cold',
      'Pneumonia',
    ]
  },
  {
    "name": "Barsati Sandipa",
    "phone": 913850460092,
    "lat": 37.40475955187059,
    "long": -122.10067863393948,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": ['Urinary tract infection', 'Psoriasis', 'Impetigo']
  },
  {
    "name": "Dharmadhrt Jonas",
    "phone": 913853240861,
    "lat": 37.430874732906034,
    "long": -122.10858679761286,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": [
      'Cervical spondylosis',
      'Paralysis (brain hemorrhage)',
      'Jaundice',
    ]
  },
  {
    "name": "Dharmesh Ambre",
    "phone": 913853240861,
    "lat": 37.41401660722154,
    "long": -122.06613244526108,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": ['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis']
  },
];
