import 'package:flutter/material.dart';

const kStyle = TextStyle(fontSize: 20.0, fontWeight: FontWeight.bold);
List<String> symptoms = [
  ' abdominal_pain',
  ' abnormal_menstruation',
  ' acidity',
  ' acute_liver_failure',
  ' altered_sensorium',
  ' anxiety',
  ' back_pain',
  ' belly_pain',
  ' blackheads',
  ' bladder_discomfort',
  ' blister',
  ' blood_in_sputum',
  ' bloody_stool',
  ' blurred_and_distorted_vision',
  ' breathlessness',
  ' brittle_nails',
  ' bruising',
  ' burning_micturition',
  ' chest_pain',
  ' chills',
  ' cold_hands_and_feets',
  ' coma',
  ' congestion',
  ' constipation',
  ' continuous_feel_of_urine',
  ' continuous_sneezing',
  ' cough',
  ' cramps',
  ' dark_urine',
  ' dehydration',
  ' depression',
  ' diarrhoea',
  ' dischromic _patches',
  ' distention_of_abdomen',
  ' dizziness',
  ' drying_and_tingling_lips',
  ' enlarged_thyroid',
  ' excessive_hunger',
  ' extra_marital_contacts',
  ' family_history',
  ' fast_heart_rate',
  ' fatigue',
  ' fluid_overload',
  ' foul_smell_of urine',
  ' headache',
  ' high_fever',
  ' hip_joint_pain',
  ' history_of_alcohol_consumption',
  ' increased_appetite',
  ' indigestion',
  ' inflammatory_nails',
  ' internal_itching',
  ' irregular_sugar_level',
  ' irritability',
  ' irritation_in_anus',
  ' joint_pain',
  ' knee_pain',
  ' lack_of_concentration',
  ' lethargy',
  ' loss_of_appetite',
  ' loss_of_balance',
  ' loss_of_smell',
  ' malaise',
  ' mild_fever',
  ' mood_swings',
  ' movement_stiffness',
  ' mucoid_sputum',
  ' muscle_pain',
  ' muscle_wasting',
  ' muscle_weakness',
  ' nausea',
  ' neck_pain',
  ' nodal_skin_eruptions',
  ' obesity',
  ' pain_behind_the_eyes',
  ' pain_during_bowel_movements',
  ' pain_in_anal_region',
  ' painful_walking',
  ' palpitations',
  ' passage_of_gases',
  ' patches_in_throat',
  ' phlegm',
  ' polyuria',
  ' prominent_veins_on_calf',
  ' puffy_face_and_eyes',
  ' pus_filled_pimples',
  ' receiving_blood_transfusion',
  ' receiving_unsterile_injections',
  ' red_sore_around_nose',
  ' red_spots_over_body',
  ' redness_of_eyes',
  ' restlessness',
  ' runny_nose',
  ' rusty_sputum',
  ' scurring',
  ' shivering',
  ' silver_like_dusting',
  ' sinus_pressure',
  ' skin_peeling',
  ' skin_rash',
  ' slurred_speech',
  ' small_dents_in_nails',
  ' spinning_movements',
  ' spotting_ urination',
  ' stiff_neck',
  ' stomach_bleeding',
  ' stomach_pain',
  ' sunken_eyes',
  ' sweating',
  ' swelled_lymph_nodes',
  ' swelling_joints',
  ' swelling_of_stomach',
  ' swollen_blood_vessels',
  ' swollen_extremeties',
  ' swollen_legs',
  ' throat_irritation',
  ' toxic_look_(typhos)',
  ' ulcers_on_tongue',
  ' unsteadiness',
  ' visual_disturbances',
  ' vomiting',
  ' watering_from_eyes',
  ' weakness_in_limbs',
  ' weakness_of_one_body_side',
  ' weight_gain',
  ' weight_loss',
  ' yellow_crust_ooze',
  ' yellow_urine',
  ' yellowing_of_eyes',
  ' yellowish_skin',
  'itching'
];

List<dynamic> doctors = [
//in mumbai
  {
    "name": "Nikhat Nachik",
    "phone": 12346798,
    "lat": 19.102045754631167,
    "long": 72.92839706288086,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": ['Fungal infection', 'Jaundice', 'Diabetes', 'Migraine']
  },
  {
    "name": "Stanley",
    "phone": 12346798,
    "lat": 19.10889895232196,
    "long": 72.90565192925476,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": ['Malaria', 'Jaundice', 'Chicken pox', 'Typhoid']
  },
  {
    "name": "Basudha Selvi",
    "phone": 12346798,
    "lat": 19.09042548238461,
    "long": 72.9047306401247,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": ['Dengue', 'Hyperthyroidism', 'Diabetes', 'Migraine']
  },
  //----usa,mountainview
  {
    "name": "Suprakash Vaishnavi",
    "phone": 12346798,
    "lat": 37.18331992252706,
    "long": -122.34539970651653,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": ['Hepatitis B', 'Alcoholic hepatitis', 'Diabetes', 'Migraine']
  },
  {
    "name": "Dharma Niramitra",
    "phone": 12346798,
    "lat": 37.1359789304352,
    "long": -122.22166559337278,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": ['Fungal infection', 'Jaundice', 'Diabetes', 'Migraine']
  },
//-----
  {
    "name": "Nikhat Nachik",
    "phone": 12346798,
    "lat": 37.42094943232773,
    "long": -122.08710571255817,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": ['Fungal infection', 'Diabetes', 'Migraine']
  },
  {
    "name": "Stanley",
    "phone": 12346798,
    "lat": 37.42466439200042,
    "long": -122.10238357592841,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": ['Malaria', 'Jaundice', 'Chicken pox', 'Typhoid']
  },
  {
    "name": "Basudha Selvi",
    "phone": 12346798,
    "lat": 37.40788284565721,
    "long": -122.0967598905863,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": ['Dengue', 'Hyperthyroidism', 'Diabetes', 'Migraine']
  },
  //----
  {
    "name": "Suprakash Vaishnavi",
    "phone": 12346798,
    "lat": 37.18331992252706,
    "long": -122.34539970651653,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": ['Hepatitis B', 'Alcoholic hepatitis', 'Diabetes', 'Migraine']
  },
  {
    "name": "Dharma Niramitra",
    "phone": 12346798,
    "lat": 37.1359789304352,
    "long": -122.22166559337278,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": ['Fungal infection', 'Diabetes', 'Migraine']
  },
  {
    "name": "Akmal Lahiri",
    "phone": 12346798,
    "lat": 37.01351077265561,
    "long": -121.98484730401294,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": ['Fungal infection', 'Jaundice', 'Diabetes', 'Migraine']
  },
  {
    "name": "Ashraf Labhsha",
    "phone": 12346798,
    "lat": 36.977397477983786,
    "long": -121.94191304052721,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": ['Fungal infection', 'Jaundice', 'Diabetes', 'Migraine']
  },
  {
    "name": "Pandhari Tatavarti",
    "phone": 12346798,
    "lat": 36.970372961376505,
    "long": -121.96933147642106,
    "opening": "2:00 pm",
    "closing": "3:00pm",
    "diseases": ['Fungal infection', 'Jaundice', 'Diabetes', 'Migraine']
  }
];
